# Generated by Django 4.2.6 on 2023-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpeg', upload_to='profile_pictures/'),
        ),
    ]
