# Generated by Django 4.2.6 on 2023-10-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_history_books'),
        ('users', '0009_user_history_books'),
    ]

    operations = [
    ]
