# Generated by Django 4.2.6 on 2023-10-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_reply_theme_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
