# Generated by Django 4.2.5 on 2023-10-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_reply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='total_reply',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
