# Generated by Django 4.2.6 on 2023-10-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_review_book_id_delete_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="book_id",
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
