# Generated by Django 4.2.6 on 2023-10-27 06:27

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):
    def load_initial_books(apps, schema_editor):
        call_command("loaddata", "initial_books.json")

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_initial_books)]
