# Generated by Django 4.2.6 on 2023-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231028_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
