# Generated by Django 4.2.6 on 2023-10-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_has_read_hasreadbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HasReadBook',
        ),
    ]
