# Generated by Django 4.2.6 on 2023-10-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_requestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
