# Generated by Django 4.2.6 on 2023-10-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_has_read'),
        ('book', '0005_requestbook_user'),
    ]

    operations = [
    ]
