name: Deploy to PythonAnywhere

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10 # Choose your Python version

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Deploy to PythonAnywhere
              run: |
                  # Use PythonAnywhere Web app's API token and URL
                  PA_TOKEN=${{ secrets.PYTHON_ANYWHERE_TOKEN }}
                  PA_URL="https://www.pythonanywhere.com"

                  # Deploy your Django app to PythonAnywhere using PA API
                  pa_autoconfigure.py https://github.com/PBP-E14/book-buddies.git

                  # Reload your web app to apply changes
                  curl -s -X POST $PA_URL/api/v0/user/irfankamil/webapps/irfankamil.pythonanywhere.com/reload/ -H "Authorization: Token $PA_TOKEN"
