name: Deploy to Fly.io

on:
    push:
        branches:
            - main

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4

            - name: Install Fly
              run: curl -L https://fly.io/install.sh | sh

            - name: Fly help
              run: /home/runner/.fly/bin/flyctl --help

            - name: Launch Fly
              run: fly launch

            - name: Deploy to Fly
              run: fly deploy
