name: Deploy to Fly.io
on:
    push:
        branches:
            - main
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4

            - name: Install Fly
              run: curl -L https://fly.io/install.sh | sh

            - name: Deploy to Fly
              run: FLY_API_TOKEN=$(/home/runner/.fly/bin/flyctl tokens create deploy) /home/runner/.fly/bin/flyctl deploy

            - name: Build Docker image
              run: |
                  docker build \
                  --build-arg ENVIRONMENT=${{ secrets.ENVIRONMENT }} \
                  -t my-app .
