name: Deploy to PythonAnywhere

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Update Ubuntu
              run: sudo apt-get update

            - name: Install Python
              run: sudo apt-get install python3.6

            - name: Install venv
              run: python3 -m venv env

            - name: Navigate To venv
              run: source env/bin/activate

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Migrate
              run: python3 manage.py migrate

            - name: Install pa_autoconfigure.py
              run: pip3.6 install --user pythonanywhere

            - name: Deploy to PythonAnywhere
              run: |
                  # Use PythonAnywhere Web app's API token and URL
                  PA_TOKEN=${{ secrets.PYTHON_ANYWHERE_TOKEN }}
                  PA_URL="https://www.pythonanywhere.com"

                  # Deploy your Django app to PythonAnywhere using PA API
                  pa_autoconfigure.py https://github.com/PBP-E14/book-buddies.git

                  # Reload your web app to apply changes
                  curl -s -X POST $PA_URL/api/v0/user/irfankamil/webapps/irfankamil.pythonanywhere.com/reload/ -H "Authorization: Token $PA_TOKEN"
