name: Django Check

on:
    push:
        branches:
            - development
    pull_request:
        branches:
            - development

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Update Ubuntu
              run: sudo apt-get update

            - name: Install Python
              run: sudo apt-get install python3.6

            - name: Install venv
              run: python3 -m venv env

            - name: Navigate To venv
              run: source env/bin/activate

            - name: Install Requirements
              run: pip install -r requirements.txt

            - name: Check if Django Application is Running
              id: check_status
              run: |
                  if [ python manage.py runserver ]; then
                      echo "Application is running."
                      echo "::set-output name=app_running::true"
                  else
                      echo "Application is not running."
                      echo "::set-output name=app_running::false"
                  fi

            - name: End Job If App is Running
              if: steps.check_status.outputs.app_running == 'true'
              run: |
                  echo "Exiting job because the application is already running."
                  exit 0
